language: python
python:
    - 2.7
    - pypy
before_install: pip freeze
install:
    - pip install -U "pip>=1.4" "setuptools>=0.9" "wheel>=0.21"
    - python setup.py sdist bdist_egg bdist_wheel install
script:
    - python test_unittest.py
